package dev.erst.gridgrind.authoring;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Incremental-build compatibility shim for the historical monolithic authoring coverage class.
 *
 * <p>The authoring test surface is now split into focused files, but keeping this class name stable
 * prevents stale compiled test artifacts from surviving no-clean builds after the split.
 */
class AuthoringApiCoverageTest {
  @TempDir Path tempDir;

  @Test
  void coversGridGrindPlanLifecycleAndRunOverloads() throws Exception {
    assertDoesNotThrow(
        () -> {
          GridGrindPlanTest tests = new GridGrindPlanTest();
          tests.tempDir = tempDir;
          tests.serializesOneFluentPlanBackToTheCanonicalWorkbookPlan();
          tests.preservesImportedCanonicalExecutionFieldsAtTheBoundary();
          tests.journalPreservesImportedExecutionModeAndCalculation();
          tests.importedPlansContinueAutoGeneratedCountersAndRespectNamedSteps();
          tests.conveniencePersistenceMethodsCoverInMemoryAndOverwriteBranches();
          tests.runsOneTableAwareOfficeWorkflowWithExplicitExecutor();
        });
  }

  @Test
  void coversGridGrindPlanConvenienceOverloads() throws Exception {
    assertDoesNotThrow(
        () -> {
          GridGrindPlanTest tests = new GridGrindPlanTest();
          tests.tempDir = tempDir;
          tests.shippedJavaAuthoringExampleCompilesAgainstThePublishedApi();
          AuthoringPublicSurfaceTest publicSurface = new AuthoringPublicSurfaceTest();
          publicSurface.compiledAuthoringModuleNoLongerRequiresExecutorTransitively();
          publicSurface.gridGrindPlanStopsAtTheCanonicalBoundary();
          publicSurface.checksAndQueriesAreNoLongerPublicApiSurface();
          publicSurface.exportedPublicTypesDoNotExposeExecutorOrRawComplexContractTypes();
        });
  }

  @Test
  void coversChecksQueriesValuesAndPlannedSteps() throws Exception {
    assertDoesNotThrow(
        () -> {
          AuthoringInternalsCoverageTest internals = new AuthoringInternalsCoverageTest();
          internals.plannedStepsPreserveExplicitIdsAndRejectInvalidInputs();
          internals.checksCoverAllSupportedAssertionHelpers();
          internals.queriesCoverAllSupportedInspectionHelpers();

          AuthoringValueCoverageTest values = new AuthoringValueCoverageTest();
          values.linksCoverFactoriesConversionsAndNullValidation();
          values.tablesCoverFactoriesConversionsAndNullValidation();
          values.valuesRejectNullsForFocusedWrappers();
          values.valuesConvertTypedCellInputsAcrossEverySupportedBranch();
          values.valuesConvertCommentsExpectedValuesAndTextSources();
        });
  }

  @Test
  void coversTargetFactoriesAcrossWorkbookEntities() throws Exception {
    assertDoesNotThrow(
        () -> {
          AuthoringTargetCoverageTest targets = new AuthoringTargetCoverageTest();
          targets.targetFactoriesExposeTheExpectedSelectors();
          targets.workbookSheetCellRangeAndWindowTargetsCoverTheirSurface();
          targets.tableNamedRangeChartAndPivotTargetsCoverTheirSurface();
          targets.targetRefsRejectNullSelectorsImmediately();
        });
  }
}
