name: Gradle wrapper validation

on:
  push:
    branches: [main]
    paths:
      - gradle/wrapper/gradle-wrapper.jar
      - gradle/wrapper/gradle-wrapper.properties
      - gradlew
      - gradlew.bat
      - .github/workflows/gradle-wrapper-validation.yml
  pull_request:
    branches: [main]
    paths:
      - gradle/wrapper/gradle-wrapper.jar
      - gradle/wrapper/gradle-wrapper.properties
      - gradlew
      - gradlew.bat
      - .github/workflows/gradle-wrapper-validation.yml

jobs:
  validate:
    name: Validate wrapper
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: gradle/actions/wrapper-validation@f236b35da9d031e13b1005234ebe4392ed54c580 # v5.0.0
